_extends: .github

repository:
  name: parakeetx
  description: Echo server for TCP/UDP/HTTP
  topics: debug,echo,http,mock,parakeet,parakeetx,server,tcp,udp
  homepage: https://github.com/harindaka/parakeet
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
